# Generated by Django 4.2 on 2023-04-16 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_lead"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("scheduled_time", models.DateTimeField()),
                (
                    "connected_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.connectedemail",
                    ),
                ),
                ("leads", models.ManyToManyField(to="app.lead")),
            ],
        ),
    ]
