# Generated by Django 4.2 on 2023-04-16 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_connectedemail_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectedemail",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.user"
            ),
        ),
    ]
