# Generated by Django 4.2 on 2023-04-17 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_connectedemail_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectedemail",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="connectedemail",
            name="client_id",
        ),
        migrations.RemoveField(
            model_name="connectedemail",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="connectedemail",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="connectedemail",
            name="refresh_token",
        ),
        migrations.RemoveField(
            model_name="connectedemail",
            name="secret_key",
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="imap_password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="imap_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="oauth2_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="smtp_password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="smtp_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
