# Generated by Django 4.2 on 2023-04-17 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_connectedemail_access_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectedemail",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="connectedemail",
            name="email",
        ),
        migrations.RemoveField(
            model_name="connectedemail",
            name="email_provider",
        ),
        migrations.RemoveField(
            model_name="connectedemail",
            name="oauth2_token",
        ),
        migrations.RemoveField(
            model_name="connectedemail",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="connectedemail",
            name="user",
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="access_token",
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="client_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="email_address",
            field=models.CharField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="imap_host",
            field=models.CharField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="imap_port",
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="provider_name",
            field=models.CharField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="refresh_token",
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="secret_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="smtp_host",
            field=models.CharField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="smtp_port",
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="token_expiry",
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="connectedemail",
            name="imap_password",
            field=models.CharField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="connectedemail",
            name="imap_username",
            field=models.CharField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="connectedemail",
            name="smtp_password",
            field=models.CharField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="connectedemail",
            name="smtp_username",
            field=models.CharField(),
            preserve_default=False,
        ),
    ]
