# Generated by Django 4.2 on 2023-04-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_connectedemail_imap_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectedemail",
            name="imap_port",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="connectedemail",
            name="smtp_port",
            field=models.CharField(max_length=200),
        ),
    ]
